apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: practica
spec:
  selector:
    matchLabels:
      app: database
  serviceName: svc-db-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: 
                  - microservice
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      terminationGracePeriodSeconds: 10
      containers:
      - name: backend
        image: valande/backend
        envFrom:
        - configMapRef:
            name: database-config
        - secretRef:
            name: private
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
          requests:
            memory: "50Mi"
            cpu: "25m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 4Gi
