services:

  svc-database:
    build: 
      context: ./dbinit
      dockerfile: ../docker/backend-dockerfile
    image: $DB_IMAGE
    networks:
      - $NETWORK_NAME
    ports:
      - $DB_TUNNEL_PORT:$DB_PORT
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: $DB_PGDATA
    volumes:
      - pg-data:$DB_VOLUME_DIR
    restart: unless-stopped

  microservice:
    build: 
      context: ./microservice
      dockerfile: ../docker/microservice-dockerfile
    image: $APP_IMAGE
    depends_on:
      - svc-database
    networks:
      - $NETWORK_NAME
    ports:
      - $APP_TUNNEL_PORT:$APP_PORT
    environment:
      FLASK_APP: $FLASK_APP
      FLASK_RUN_HOST: $FLASK_RUN_HOST
      FLASK_DEBUG: $FLASK_DEBUG
      DB_SERVICE: $DB_SERVICE
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    restart: unless-stopped
    
volumes:
  pg-data:
    name: pg-data

networks:
  valnet:
    name: $NETWORK_NAME
