services:
  valapp:
    build: 
      context: ./app
      dockerfile: ../Dockerfile
    image: $VALAPP_IMAGE
    depends_on:
      - valredis
    networks:
      - valnet
    ports:
      - $VALAPP_PORT_EXTERNAL:$VALAPP_PORT_INTERNAL
    environment:
      FLASK_APP: $FLASK_APP
      FLASK_RUN_HOST: $FLASK_RUN_HOST
      FLASK_DEBUG: true
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
    restart: unless-stopped

  valredis:
    image: $REDIS_IMAGE
    restart: unless-stopped
    networks:
      - valnet
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    name: redis_data

networks:
  valnet:
    name: valnet
