services:
  valapp:
    build: 
      context: ./app
      dockerfile: ../Dockerfile
    image: valande/valapp:1.0-beta
    depends_on:
      - valredis
    networks:
      - valnet
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: ./app
        target: /code
    environment:
      FLASK_APP: "valapp.py"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_DEBUG: "true"
      REDIS_HOST: "valredis"
      REDIS_PORT: "6379"
    restart: unless-stopped

  valredis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - valnet
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    name: redis_data

networks:
  valnet:
    name: valnet
