services:

  valpg:
    build: 
      context: ./db
      dockerfile: ../Dockerfile-db
    image: $DB_IMAGE
    networks:
      - $NETWORK_NAME
    ports:
      - $DB_PORT_EXTERNAL:$DB_PORT_INTERNAL
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: $DB_PGDATA
    volumes:
      - pgdata:$DB_VOLUME_DIR
    restart: unless-stopped

  valapp:
    build: 
      context: ./app
      dockerfile: ../Dockerfile-app
    image: $APP_IMAGE
    depends_on:
      - valpg
    networks:
      - $NETWORK_NAME
    ports:
      - $APP_PORT_EXTERNAL:$APP_PORT_INTERNAL
    environment:
      FLASK_APP: $FLASK_APP
      FLASK_RUN_HOST: $FLASK_RUN_HOST
      FLASK_DEBUG: $FLASK_DEBUG
      DB_HOSTNAME: $DB_HOSTNAME
      DB_PORT: $DB_PORT_INTERNAL
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    restart: unless-stopped
    
volumes:
  pgdata:
    name: pgdata

networks:
  valnet:
    name: $NETWORK_NAME
