apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: practica
spec:
  selector:
    matchLabels:
      app: microservice
  replicas: 3
  template:
    metadata:
      labels:
        app: microservice
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: 
                  - database
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: 
                  - microservice
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
      - name: microservice
        image: valande/microservice
        envFrom:
        - configMapRef:
            name: microservice-config
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: private
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: private
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_DB
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DB_PORT
        ports:
        - containerPort: 5000
          name: microservice
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
          requests:
            memory: "50Mi"
            cpu: "25m"

