apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-mount-volume
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c" ]
      args: 
        - ls /etc/config/
        - cat /etc/config/SPECIAL_LEVEL
        - cat /etc/config/SPECIAL_TYPE
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config-multi
  restartPolicy: Never
