apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: practica
data:
  APP_PORT: "5000"
  APP_TUNNEL_PORT: "8000"
  FLASK_APP: valapp.py
  FLASK_DEBUG: "true"
  FLASK_RUN_HOST: "0.0.0.0"
  DB_HOSTNAME: svc-database
  DB_PORT: "5432"
