apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: practica
spec:
  selector:
    matchLabels:
      app: valapp
  replicas: 3
  template:
    metadata:
      labels:
        app: valapp
    spec:
      containers:
      - name: valapp
        image: valande/valapp:1.0
        envFrom:
        - configMapRef:
            name: appconfig
        ports:
        - containerPort: 5000
