apiVersion: v1
kind: Service
metadata:
  name: valdb-headless
  labels:
    app: nginx
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  serviceName: "valdb-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: valdb
        image: valande/valdb:1.0
        envFrom:
        - configMapRef:
            name: dbconfig
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: dbvol
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: dbvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 4Gi