# ----------------------------------------------------------------------
FROM postgres:15.2-alpine3.17

LABEL version=1.0-pg-beta \
      description="Imagen DB para practica Contenedores y Kubernetes" \
      mantainer="Valande <valande@gmail.com>"

COPY ./*.sh /docker-entrypoint-initdb.d/

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]
CMD [ "postgres" ]
