# ----------------------------------------------------------------------
FROM python:3.7-alpine as compile-stage

RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers

WORKDIR /code
COPY ./requirements.txt ./requirements.txt
RUN pip install --prefix=/pyinstall -r requirements.txt 
    
# ----------------------------------------------------------------------
FROM python:3.7-alpine as runtime

LABEL version=1.0-pg-beta \
      description="Imagen APP para practica Contenedores y Kubernetes" \
      mantainer="Valande <valande@gmail.com>"

COPY --from=compile-stage /pyinstall /usr/local
WORKDIR /code
COPY . .
RUN rm ./requirements.txt && \
    addgroup -S appuser && \
    adduser -S appuser -G appuser && \
    chown -R appuser:appuser /code

USER appuser

ENV DB_PORT=5432
ENV DB_SERVICE=svc-database
ENV DB_NAME=flask_db
ENV DB_USERNAME=dbuser
ENV DB_PASSWORD=dbpass
ENV FLASK_APP=valapp.py
ENV FLASK_DEBUG=true
ENV FLASK_RUN_HOST=0.0.0.0
EXPOSE 5000

CMD ["flask", "run"]
