apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-nginx.fullname" . }}
  labels:
    {{- include "demo-nginx.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo-nginx.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "demo-nginx.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: www-volumen
          configMap:
            name: {{ include "demo-nginx.fullname" . }}-cm
      containers:
        - name: nginx
          image: "{{ .Values.imagen }}"
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: {{ .Values.cpuRequest }}
            limits:
              cpu: {{ .Values.cpuLimit }}
          volumeMounts:
            - name: www-volumen
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
