apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-nginx.fullname" . }}-svc
  labels:
    {{- include "demo-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "demo-nginx.selectorLabels" . | nindent 4 }}