apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice
  namespace: practica
spec:
  maxReplicas: 20
  minReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice
