apiVersion: v1
kind: Service
metadata:
  name: my-service
  # Mediante annotations podemos exponer el service en un balanceador interno (GKE)
  #annotations:
  #  cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
