apiVersion: v1
kind: Service
metadata:
  name: {{ include "contkube.fullname" . }}-svc-app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: microservice
spec:
  selector:
    {{- include "contkube.selectorLabels" . | nindent 4 }}
    app: microservice
  type: {{ .Values.service.microservice.type }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  