apiVersion: v1
kind: Service
metadata:
  #name: svc-microservice # helm-conf
  name: {{ include "contkube.fullname" . }}-sv-micro
spec:
  type: LoadBalancer # helm-conf
  selector:
    app: microservice # helm-conf
  ports:
  - protocol: TCP
    port: 5000 # helm-conf
    targetPort: 5000 # helm-conf
