apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contkube.fullname" . }}-microconf
  namespace: practica
data:
  APP_PORT: "5000" # helm-conf
  APP_TUNNEL_PORT: "8000" # helm-conf
  FLASK_APP: valapp.py
  FLASK_DEBUG: "true" # helm-conf
  FLASK_RUN_HOST: "0.0.0.0"
  DB_SERVICE: svc-database # helm-conf
