apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contkube.fullname" . }}-app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: microservice
spec:
  selector:
    matchLabels:
      {{- include "contkube.selectorLabels" . | nindent 6 }}
      app: microservice
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "contkube.selectorLabels" . | nindent 8 }}
        app: microservice
    spec:
      containers:
      - name: c-app
        image: {{ .Values.images.microservice }}
        envFrom:
        - configMapRef:
            name: {{ include "contkube.fullname" . }}-appconf
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "contkube.fullname" . }}-dbconf
              key: POSTGRES_DB
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "contkube.fullname" . }}-dbconf
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "contkube.fullname" . }}-priv
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "contkube.fullname" . }}-priv
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5000
          name: app-port
