apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contkube.fullname" . }}-dbconf
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: database
data:
  DB_PORT: "5432"
  {{- with .Values.config.database }}
  DB_TUNNEL_PORT:  {{ .tunnelport | quote }}
  POSTGRES_DB:  {{ .dbname }}
  PGDATA:  {{ .pgdata }}
  {{- end }}
  {{- with .Values.volumeMount }}
  DB_VOLUME_DIR:  {{ .path }}
  {{- end }}
  