apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contkube.fullname" . }}-dbconf
  namespace: practica
data:
  DB_TUNNEL_PORT: "7777" # helm-conf
  DB_PORT: "5432" # helm-conf
  DB_VOLUME_DIR: /var/lib/postgresql/data
  POSTGRES_DB: flask_db
  PGDATA: /var/lib/postgresql/data/pgdata
  