apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contkube.fullname" . }}-dbconf
  namespace: {{ .Values.namespace }}
data:
  DB_PORT: "5432"
  {{- with .Values.config.database }}
  DB_TUNNEL_PORT:  {{ .tunnelport | quote }}
  DB_VOLUME_DIR:  {{ .volume }}
  POSTGRES_DB:  {{ .dbname }}
  PGDATA:  {{ .pgdata }}
  {{- end }}
  