apiVersion: v1
kind: Service
metadata:
  name: svc-database # helm-conf
spec:
  type: LoadBalancer # helm-conf
  selector:
    app: database # helm-conf
  ports:
  - protocol: TCP
    port: 5432 # helm-conf
    targetPort: 5432 # helm-conf
