apiVersion: v1
kind: Service
metadata:
  name: {{ include "contkube.fullname" . }}-svc-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: database
spec:
  type: {{.Values.service.database.type }}
  selector:
    {{- include "contkube.selectorLabels" . | nindent 4 }}
    app: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
