apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database # helm-conf
spec:
  selector:
    matchLabels:
      app: database # helm-conf
  serviceName: svc-db-headless # helm-conf
  replicas: 1
  template:
    metadata:
      labels:
        app: database # helm-conf
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: backend
        image: valande/backend # helm-conf
        envFrom:
        - configMapRef:
            name: {{ include "contkube.fullname" . }}-dbconf
        - secretRef:
            name: {{ include "contkube.fullname" . }}-private
        ports:
        - containerPort: 5432 # helm-conf
          name: database
        volumeMounts: # helm-conf
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates: # helm-conf
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 4Gi
