apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "contkube.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: database
spec:
  selector:
    matchLabels:
      {{- include "contkube.selectorLabels" . | nindent 6 }}
      app: database
  serviceName: {{ include "contkube.fullname" . }}-svc-hldb
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "contkube.selectorLabels" . | nindent 8 }}
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: c-db
        image: {{ .Values.images.database }}
        envFrom:
        - configMapRef:
            name: {{ include "contkube.fullname" . }}-dbconf
        - secretRef:
            name: {{ include "contkube.fullname" . }}-priv
        ports:
        - containerPort: 5432
          name: db-port
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 4Gi
