apiVersion: v1
kind: Service
metadata:
  name: {{ include "contkube.fullname" . }}-svc-hldb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: database
spec:
  ports:
  - port: 5432
    name: headless
  clusterIP: None
  selector:
    {{- include "contkube.selectorLabels" . | nindent 4 }}
    app: database
