apiVersion: v1
kind: Service
metadata:
  name: svc-db-headless # helm-conf
  labels:
    app: database # helm-conf
spec:
  ports:
  - port: 5432 # helm-conf
    name: headless
  clusterIP: None
  selector:
    app: database # helm-conf
