apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contkube.fullname" . }}-priv
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contkube.labels" . | nindent 4 }}
    app: credentials
type: Opaque
data:
  {{- with .Values.config.database }}
  POSTGRES_USER: {{ .user }} 
  POSTGRES_PASSWORD: {{ .password }}
  {{- end }}
