apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contkube.fullname" . }}-private # helm-conf
  namespace: practica
type: Opaque
data:
  {{- with .Values.config.database.private }}
  POSTGRES_PASSWORD: {{ .user }} 
  POSTGRES_USER: {{ .password }}
  {{- end }}
