namespace: practica

images:
  microservice: valande/microservice
  database: valande/backend

replicaCount: 3

config:
  microservice:
    tunnelport: 5000
    debug: true
    host: 0.0.0.0
  database:
    terminationGrace: 10
    tunnelport: 5432
    dbname: flask_db
    pgdata: /var/lib/postgresql/data/pgdata
    user: ZGJ1c2Vy
    password: ZGJwYXNz

service:
  microservice:
    type: LoadBalancer
  database:
    type: LoadBalancer

volumeMount:
  enabled: true
  path: /var/lib/postgresql/data
  name: data
  volumename:
  size: 4Gi
  storageclass: "standard"