apiVersion: v1
kind: Service
metadata:
  name: svc-db-headless
  namespace: practica
  labels:
    app: database
spec:
  ports:
  - port: 5432
    name: headless
  clusterIP: None
  selector:
    app: database
